import Head from 'next/head';
import styles from '../styles/Home.module.css';
import React, { useEffect, useState } from 'react';
import FirebaseInstance from '../services/firebase/firebase';
import FirebaseSignin from './components/firebase-signin';

export default function Home() {
    const [isSignedIn, setIsSignedIn] = useState(false); // Local signed-in state.
    // Listen to the Firebase Auth state and set the local state.
    useEffect(() => {
        const unregisterAuthObserver = FirebaseInstance()
            .auth()
            .onAuthStateChanged((user) => {
                setIsSignedIn(!!user);
            });
        return () => unregisterAuthObserver(); // Make sure we un-register Firebase observers when the component unmounts.
    }, []);

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                {!isSignedIn ? (
                    <FirebaseSignin firebase={FirebaseInstance()} />
                ) : (
                    <div>
                        <h1>My App</h1>
                        <p>
                            Welcome {FirebaseInstance().auth().currentUser.displayName}!
                            You are now signed-in!
                        </p>
                        <a onClick={() => FirebaseInstance().auth().signOut()}>
                            Sign-out
                        </a>
                    </div>
                )}
            </main>

            <footer className={styles.footer}></footer>
        </div>
    );
}
